### ISSUE TITLE
Update "About" Section

### ISSUE THREAD

**Issue by jeremytackett** [kalebheitzman/how2charist#35]

**Comment by kalebheitzman** [comment]
How2charist is much more than a tool for formation and evangelism; it's a dream that has been in the making for over a decad! In 2008, project creator Callie Swanlund took a seminary course called New Media in Worship & Preaching with the Rev. Dr. Micah Jackson. Micah issued a challenge for students to create projects which incorporated new forms of media into worship, because the church had been using media in the form of icons for centuries. Callie used the foundation of an instructed eucharist—in which the history of the eucharistic rite and the symbolism of the service are explained in narrative form—to make a more seamless liturgy that was stimulating and enlightening. Taking inspiration from VH1's Pop-Up Video series, the How2charist was born.

While the early PowerPoint version was edifying and enjoyable, many friends, colleagues, and parishioners asked whether this was something that could be made available more broadly. Callie dreamed of partnering with someone who could bring the technical background to make this a reality. Fast forward several years, and enter [Jeremy Tackett](https://jeremytackett.com). As Callie excitedly explained my vision of sharing a live How2charist, Jeremy immediately jumped on board and started naming off the numerous pieces of equipment and tech assistants he'd need. They both saw each other's excitement and knew this project needed to be something easily accessible by individuals, churches, seminaries, schools, dioceses, and more. Most importantly, it needed to preserve the beauty of the Book of Common Prayer liturgy, be informative and prayerful, be of a quality that would make it a shareable resource for the whole Church, and draw people closer to God.

In 2018, in partnership with [The Episcopal Church's](https://www.episcopalchurch.org/) digital evangelism team, plans were made to launch the How2charist project Kickstarter. The crowd-funding model generated communal excitement, ensured the resource would be available to all, and was wildly successful (raising over $30,000). Because of the partnership between Callie and The Episcopal Church, the How2charist project can serve as a model to support individuals, parishes, and dioceses as they innovate and create new ways to reach folks. The basis for the partnership was that raising financial support to make the project viable was the responsibility of the project's creator, and the digital evangelism team supported the project by providing guidance and technical direction, resourcing with other offices as needed (from formation to evangelism to tech), and by giving the tools needed to launch and scale the idea for a larger audience.

After the Kickstarter was fully funded, there was a push to raise more money as a seed for filming a second version in Spanish. The English version was filmed in Philadelphia, PA, in August 2018, and the Spanish version was filmed in Los Angeles, CA, in November 2018 (with release anticipated in Spring 2019). At each step of the way, How2charist fans have expanded the original project idea into an even bigger challenge and dream, and the future journey for How2charist is yet to be seen!

This is a communal resource: made possible by the financial support and talents of many, and given as a gift for all. Callie and the Office of Communication at The Episcopal Church can't wait to see the ways in which individuals and churches co-create ways of evangelizing the Gospel and deepening faith through the How2charist!

**Comment by kalebheitzman** [comment]
added with efad3c9 and #46
